config/routes.rb
Rails.application.routes.draw do

  resources :user_agents

  root 'user_agents#index'

end

app/models/user_agent.rb
class UserAgent < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :find_or_create_user_agent

  def find_or_create_user_agent
    unless request.xhr?
      user_agent_name = request.user_agent
      user_agent = UserAgent.find_or_create_by(name: user_agent_name) if user_agent_name
      increment = user_agent.counter + 1
      user_agent.update(counter: increment)
    end
  end
end

app/controllers/user_agents_controller.rb
class UserAgentsController < ApplicationController

  def index
    @user_agents = UserAgent.all.order(:created_at)

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserAgentDetector</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_agents/_table.html.haml
:ruby
  user_agents = @user_agents || user_agents

%table{:width => "90%"}
  %tr
    %th User Agent Name
    %th Counter
    %th First Created
    %th Last Seen
    - user_agents.each do |user_agent|
      %tr
        %td{:width => "40%"}= user_agent.name
        %td{:width => "10%", :align => "center"}= user_agent.counter
        %td{:width => "25%", :align => "center"}= user_agent.created_at
        %td{:width => "25%", :align => "center"}= user_agent.updated_at

= button_to "Refresh", user_agents_path, class: "update", remote: true, method: :get

app/views/user_agents/index.html.haml
%h3 User Agents

.agent-table
  = render 'table'

app/views/user_agents/index.js.erb
$(".agent-table").html("<%= escape_javascript(render partial: 'table', locals: { user_agents: @user_agents } ) %>");